# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: curie_extensions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='curie_extensions.proto',
  package='nutanix.curie',
  syntax='proto2',
  serialized_pb=_b('\n\x16\x63urie_extensions.proto\x12\rnutanix.curie\x1a google/protobuf/descriptor.proto:F\n\x15\x64\x65\x66\x61ult_timeout_msecs\x12\x1f.google.protobuf.ServiceOptions\x18\xb8\x8e\x03 \x01(\x05:\x04\x31\x30\x30\x30:A\n\x13\x64\x65\x66\x61ult_max_retries\x12\x1f.google.protobuf.ServiceOptions\x18\xb9\x8e\x03 \x01(\x05:\x01\x30:7\n\rtimeout_msecs\x12\x1e.google.protobuf.MethodOptions\x18\xc8\xdc\x03 \x01(\x05:5\n\x0bmax_retries\x12\x1e.google.protobuf.MethodOptions\x18\xc9\xdc\x03 \x01(\x05:2\n\tencrypted\x12\x1d.google.protobuf.FieldOptions\x18\x80\xf1\x04 \x01(\x08')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DEFAULT_TIMEOUT_MSECS_FIELD_NUMBER = 51000
default_timeout_msecs = _descriptor.FieldDescriptor(
  name='default_timeout_msecs', full_name='nutanix.curie.default_timeout_msecs', index=0,
  number=51000, type=5, cpp_type=1, label=1,
  has_default_value=True, default_value=1000,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
DEFAULT_MAX_RETRIES_FIELD_NUMBER = 51001
default_max_retries = _descriptor.FieldDescriptor(
  name='default_max_retries', full_name='nutanix.curie.default_max_retries', index=1,
  number=51001, type=5, cpp_type=1, label=1,
  has_default_value=True, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
TIMEOUT_MSECS_FIELD_NUMBER = 61000
timeout_msecs = _descriptor.FieldDescriptor(
  name='timeout_msecs', full_name='nutanix.curie.timeout_msecs', index=2,
  number=61000, type=5, cpp_type=1, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
MAX_RETRIES_FIELD_NUMBER = 61001
max_retries = _descriptor.FieldDescriptor(
  name='max_retries', full_name='nutanix.curie.max_retries', index=3,
  number=61001, type=5, cpp_type=1, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)
ENCRYPTED_FIELD_NUMBER = 80000
encrypted = _descriptor.FieldDescriptor(
  name='encrypted', full_name='nutanix.curie.encrypted', index=4,
  number=80000, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  options=None)

DESCRIPTOR.extensions_by_name['default_timeout_msecs'] = default_timeout_msecs
DESCRIPTOR.extensions_by_name['default_max_retries'] = default_max_retries
DESCRIPTOR.extensions_by_name['timeout_msecs'] = timeout_msecs
DESCRIPTOR.extensions_by_name['max_retries'] = max_retries
DESCRIPTOR.extensions_by_name['encrypted'] = encrypted

google_dot_protobuf_dot_descriptor__pb2.ServiceOptions.RegisterExtension(default_timeout_msecs)
google_dot_protobuf_dot_descriptor__pb2.ServiceOptions.RegisterExtension(default_max_retries)
google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(timeout_msecs)
google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(max_retries)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(encrypted)

# @@protoc_insertion_point(module_scope)
