# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: curie_metrics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='curie_metrics.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13\x63urie_metrics.proto\"\xb4\x07\n\x0b\x43urieMetric\x12\x1f\n\x04name\x18\x01 \x02(\x0e\x32\x11.CurieMetric.Name\x12\x13\n\x0b\x64\x65scription\x18\x02 \x02(\t\x12\x1f\n\x04type\x18\x03 \x02(\x0e\x32\x11.CurieMetric.Type\x12\x31\n\rconsolidation\x18\x04 \x02(\x0e\x32\x1a.CurieMetric.Consolidation\x12\x1f\n\x04unit\x18\x05 \x02(\x0e\x32\x11.CurieMetric.Unit\x12/\n\x04rate\x18\x06 \x01(\x0e\x32\x11.CurieMetric.Rate:\x0ekInstantaneous\x12\x12\n\ntimestamps\x18\x07 \x03(\x03\x12\x0e\n\x06values\x18\x08 \x03(\x03\x12\x10\n\x08instance\x18\t \x02(\t\x12\x1b\n\x0c\x65xperimental\x18\n \x01(\x08:\x05\x66\x61lse\"\xc4\x01\n\x04Name\x12\x0e\n\tkCpuUsage\x10\xe8\x07\x12\x0e\n\tkMemUsage\x10\xd0\x0f\x12\x0f\n\nkMemActive\x10\xd1\x0f\x12\x11\n\x0ckNetReceived\x10\xb8\x17\x12\x14\n\x0fkNetTransmitted\x10\xb9\x17\x12\x1a\n\x15kDatastoreReadLatency\x10\xa0\x1f\x12\x1b\n\x16kDatastoreWriteLatency\x10\xa1\x1f\x12\x13\n\x0ekDatastoreRead\x10\xa2\x1f\x12\x14\n\x0fkDatastoreWrite\x10\xa3\x1f\" \n\x04Type\x12\n\n\x06kGauge\x10\x00\x12\x0c\n\x08kCounter\x10\x01\"8\n\rConsolidation\x12\t\n\x05kLast\x10\x00\x12\x08\n\x04kMin\x10\x01\x12\x08\n\x04kMax\x10\x02\x12\x08\n\x04kAvg\x10\x03\"\xf1\x01\n\x04Unit\x12\t\n\x05kNone\x10\x00\x12\x0f\n\x0bkOperations\x10\x01\x12\x0c\n\x08kPercent\x10\x02\x12\x12\n\rkMicroseconds\x10\x90\x01\x12\x12\n\rkMilliseconds\x10\x93\x01\x12\r\n\x08kSeconds\x10\x96\x01\x12\n\n\x05kBits\x10\xc8\x01\x12\x0e\n\tkKilobits\x10\xcb\x01\x12\x0e\n\tkMegabits\x10\xce\x01\x12\x0b\n\x06kBytes\x10\xac\x02\x12\x0f\n\nkKilobytes\x10\xaf\x02\x12\x0f\n\nkMegabytes\x10\xb2\x02\x12\x0b\n\x06kHertz\x10\xc2\x03\x12\x0f\n\nkKilohertz\x10\xc5\x03\x12\x0f\n\nkMegahertz\x10\xc8\x03\"_\n\x04Rate\x12\x12\n\x0ekInstantaneous\x10\x00\x12\x13\n\x0fkPerMillisecond\x10\x61\x12\x0e\n\nkPerSecond\x10\x64\x12\x0f\n\nkPerMinute\x10\xc8\x01\x12\r\n\x08kPerHour\x10\xac\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CURIEMETRIC_NAME = _descriptor.EnumDescriptor(
  name='Name',
  full_name='CurieMetric.Name',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kCpuUsage', index=0, number=1000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kMemUsage', index=1, number=2000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kMemActive', index=2, number=2001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kNetReceived', index=3, number=3000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kNetTransmitted', index=4, number=3001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kDatastoreReadLatency', index=5, number=4000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kDatastoreWriteLatency', index=6, number=4001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kDatastoreRead', index=7, number=4002,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kDatastoreWrite', index=8, number=4003,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=343,
  serialized_end=539,
)
_sym_db.RegisterEnumDescriptor(_CURIEMETRIC_NAME)

_CURIEMETRIC_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='CurieMetric.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kGauge', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kCounter', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=541,
  serialized_end=573,
)
_sym_db.RegisterEnumDescriptor(_CURIEMETRIC_TYPE)

_CURIEMETRIC_CONSOLIDATION = _descriptor.EnumDescriptor(
  name='Consolidation',
  full_name='CurieMetric.Consolidation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kLast', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kMin', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kMax', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kAvg', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=575,
  serialized_end=631,
)
_sym_db.RegisterEnumDescriptor(_CURIEMETRIC_CONSOLIDATION)

_CURIEMETRIC_UNIT = _descriptor.EnumDescriptor(
  name='Unit',
  full_name='CurieMetric.Unit',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kNone', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kOperations', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kPercent', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kMicroseconds', index=3, number=144,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kMilliseconds', index=4, number=147,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kSeconds', index=5, number=150,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kBits', index=6, number=200,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kKilobits', index=7, number=203,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kMegabits', index=8, number=206,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kBytes', index=9, number=300,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kKilobytes', index=10, number=303,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kMegabytes', index=11, number=306,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kHertz', index=12, number=450,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kKilohertz', index=13, number=453,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kMegahertz', index=14, number=456,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=634,
  serialized_end=875,
)
_sym_db.RegisterEnumDescriptor(_CURIEMETRIC_UNIT)

_CURIEMETRIC_RATE = _descriptor.EnumDescriptor(
  name='Rate',
  full_name='CurieMetric.Rate',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kInstantaneous', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kPerMillisecond', index=1, number=97,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kPerSecond', index=2, number=100,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kPerMinute', index=3, number=200,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kPerHour', index=4, number=300,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=877,
  serialized_end=972,
)
_sym_db.RegisterEnumDescriptor(_CURIEMETRIC_RATE)


_CURIEMETRIC = _descriptor.Descriptor(
  name='CurieMetric',
  full_name='CurieMetric',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='CurieMetric.name', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='CurieMetric.description', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='CurieMetric.type', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='consolidation', full_name='CurieMetric.consolidation', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unit', full_name='CurieMetric.unit', index=4,
      number=5, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rate', full_name='CurieMetric.rate', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamps', full_name='CurieMetric.timestamps', index=6,
      number=7, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='CurieMetric.values', index=7,
      number=8, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instance', full_name='CurieMetric.instance', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='experimental', full_name='CurieMetric.experimental', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CURIEMETRIC_NAME,
    _CURIEMETRIC_TYPE,
    _CURIEMETRIC_CONSOLIDATION,
    _CURIEMETRIC_UNIT,
    _CURIEMETRIC_RATE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=972,
)

_CURIEMETRIC.fields_by_name['name'].enum_type = _CURIEMETRIC_NAME
_CURIEMETRIC.fields_by_name['type'].enum_type = _CURIEMETRIC_TYPE
_CURIEMETRIC.fields_by_name['consolidation'].enum_type = _CURIEMETRIC_CONSOLIDATION
_CURIEMETRIC.fields_by_name['unit'].enum_type = _CURIEMETRIC_UNIT
_CURIEMETRIC.fields_by_name['rate'].enum_type = _CURIEMETRIC_RATE
_CURIEMETRIC_NAME.containing_type = _CURIEMETRIC
_CURIEMETRIC_TYPE.containing_type = _CURIEMETRIC
_CURIEMETRIC_CONSOLIDATION.containing_type = _CURIEMETRIC
_CURIEMETRIC_UNIT.containing_type = _CURIEMETRIC
_CURIEMETRIC_RATE.containing_type = _CURIEMETRIC
DESCRIPTOR.message_types_by_name['CurieMetric'] = _CURIEMETRIC

CurieMetric = _reflection.GeneratedProtocolMessageType('CurieMetric', (_message.Message,), dict(
  DESCRIPTOR = _CURIEMETRIC,
  __module__ = 'curie_metrics_pb2'
  # @@protoc_insertion_point(class_scope:CurieMetric)
  ))
_sym_db.RegisterMessage(CurieMetric)


# @@protoc_insertion_point(module_scope)
