# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: curie_error.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='curie_error.proto',
  package='nutanix.curie',
  syntax='proto2',
  serialized_pb=_b('\n\x11\x63urie_error.proto\x12\rnutanix.curie\"\xb5\x02\n\nCurieError\"\xa6\x02\n\x04Type\x12\x0c\n\x08kNoError\x10\x00\x12\n\n\x06kRetry\x10\x01\x12\x0c\n\x08kTimeout\x10\x02\x12\x15\n\x11kInvalidParameter\x10\x03\x12+\n\'kManagementServerApiAuthenticationError\x10\x04\x12\x1d\n\x19kManagementServerApiError\x10\x05\x12\"\n\x1ekClusterApiAuthenticationError\x10\x06\x12\x14\n\x10kClusterApiError\x10\x07\x12\x12\n\x0ekInternalError\x10\x08\x12\x1b\n\x17kOobAuthenticationError\x10\t\x12\x18\n\x14kAuthenticationError\x10\n\x12\x0e\n\nkNumErrors\x10\x0b\"S\n\x08\x45rrorRet\x12\x33\n\x0b\x65rror_codes\x18\x01 \x03(\x0e\x32\x1e.nutanix.curie.CurieError.Type\x12\x12\n\nerror_msgs\x18\x02 \x03(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CURIEERROR_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='nutanix.curie.CurieError.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kNoError', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kRetry', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kTimeout', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kInvalidParameter', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kManagementServerApiAuthenticationError', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kManagementServerApiError', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kClusterApiAuthenticationError', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kClusterApiError', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kInternalError', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kOobAuthenticationError', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kAuthenticationError', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kNumErrors', index=11, number=11,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=52,
  serialized_end=346,
)
_sym_db.RegisterEnumDescriptor(_CURIEERROR_TYPE)


_CURIEERROR = _descriptor.Descriptor(
  name='CurieError',
  full_name='nutanix.curie.CurieError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CURIEERROR_TYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=346,
)


_ERRORRET = _descriptor.Descriptor(
  name='ErrorRet',
  full_name='nutanix.curie.ErrorRet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_codes', full_name='nutanix.curie.ErrorRet.error_codes', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_msgs', full_name='nutanix.curie.ErrorRet.error_msgs', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=431,
)

_CURIEERROR_TYPE.containing_type = _CURIEERROR
_ERRORRET.fields_by_name['error_codes'].enum_type = _CURIEERROR_TYPE
DESCRIPTOR.message_types_by_name['CurieError'] = _CURIEERROR
DESCRIPTOR.message_types_by_name['ErrorRet'] = _ERRORRET

CurieError = _reflection.GeneratedProtocolMessageType('CurieError', (_message.Message,), dict(
  DESCRIPTOR = _CURIEERROR,
  __module__ = 'curie_error_pb2'
  # @@protoc_insertion_point(class_scope:nutanix.curie.CurieError)
  ))
_sym_db.RegisterMessage(CurieError)

ErrorRet = _reflection.GeneratedProtocolMessageType('ErrorRet', (_message.Message,), dict(
  DESCRIPTOR = _ERRORRET,
  __module__ = 'curie_error_pb2'
  # @@protoc_insertion_point(class_scope:nutanix.curie.ErrorRet)
  ))
_sym_db.RegisterMessage(ErrorRet)


# @@protoc_insertion_point(module_scope)
